CREATE TABLE IF NOT EXISTS "simple_array" (
   "id" TEXT,
   "txt" TEXT,
   "ip" INET,
   "i16" SMALLINT,
   "u16" SMALLINT,
   "i32" INTEGER,
   "u32" INTEGER,
   "i32_from_text" INTEGER,
   "f32" REAL,
   "f64" DOUBLE PRECISION,
   "bool" BOOLEAN,
   "null_" TEXT,
   "array_i32" INTEGER[],
   "array_u32" INTEGER[],
   "array_text" TEXT[],
   "array_mixed" TEXT[],
   "empty_array" TEXT[],
   "empty_multi_arrays" TEXT[][],
   "datetime" TIMESTAMP WITHOUT TIME ZONE,
   "datetime_2" TIMESTAMP WITH TIME ZONE,
   "obj" TEXT,
   "vector_float" FLOAT[],
   "vector_float_simple" FLOAT[]
)